# Generated by Django 5.2.6 on 2025-11-07 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the background.', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='A short, unique code for this background.', max_length=10, unique=True)),
                ('svg_template', models.TextField(help_text='The SVG source code template for this background.')),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the fish species.', max_length=100, unique=True)),
                ('species_code', models.CharField(db_index=True, help_text="A short, unique code for programmatic access, e.g., 'C-KRAKEN'.", max_length=10, unique=True)),
                ('svg_template', models.TextField(help_text='The SVG source code template for this fish.')),
                ('evolves_from', models.ForeignKey(blank=True, help_text='The species from which this one evolves.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolves_into', to='items.fishspecies')),
            ],
        ),
        migrations.CreateModel(
            name='UserBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user unlocked this background.')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.background')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'background')},
            },
        ),
    ]
