# Generated by Django 5.2.6 on 2025-11-10 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the background.', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='A short, unique code for this background.', max_length=10, unique=True)),
                ('svg_template', models.TextField(help_text='The SVG source code template for this background.')),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the fish species.', max_length=100, unique=True)),
                ('group_code', models.CharField(db_index=True, default='NONE', help_text="A code for the evolution group, e.g., 'C-KRAKEN'.", max_length=10)),
                ('level', models.IntegerField(default=0, help_text='The evolution level of the fish, from 0 to 5.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('required_commits', models.PositiveIntegerField(db_index=True, default=0, help_text='The total number of commits required to reach this evolution level.')),
                ('svg_template', models.TextField(help_text='The SVG source code template for this fish.')),
            ],
            options={
                'unique_together': {('group_code', 'level')},
            },
        ),
    ]
