# Generated by Django 4.2.27 on 2025-12-18 14:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the background.', max_length=100, unique=True)),
                ('code', models.CharField(db_index=True, help_text='A short, unique code for this background.', max_length=10, unique=True)),
                ('background_image', models.ImageField(blank=True, help_text='배경 이미지 파일(PNG/JPG).', null=True, upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='아이템 식별 코드 (예: TICKET_REROLL)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('REROLL', 'Re-roll Ticket'), ('BG_UNLOCK', 'Background Unlock')], max_length=20)),
                ('price', models.PositiveIntegerField(default=10, help_text='구매 가격 (Points)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_active', models.BooleanField(default=True, help_text='상점 노출 여부')),
                ('target_background', models.ForeignKey(blank=True, help_text='배경 해금권일 경우 연결된 배경 객체', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.background')),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The display name of the fish species.', max_length=100, unique=True)),
                ('group_code', models.CharField(db_index=True, default='NONE', help_text="A code for the evolution group, e.g., 'C-KRAKEN'.", max_length=10)),
                ('maturity', models.IntegerField(choices=[(1, 'Hatchling'), (2, 'Juvenile'), (3, 'Youngling'), (4, 'Adult'), (5, 'Advanced'), (6, 'Master')], default=1, help_text='The evolution stage of the fish.')),
                ('required_commits', models.PositiveIntegerField(db_index=True, default=0, help_text='The total number of commits required to reach this evolution stage.')),
                ('rarity', models.IntegerField(choices=[(1, 'Common'), (2, 'Uncommon'), (3, 'Rare'), (4, 'Epic'), (5, 'Legendary')], default=1, help_text='The rarity level of the fish species.')),
                ('svg_template', models.TextField(help_text='The SVG source code template for this fish.')),
            ],
            options={
                'unique_together': {('group_code', 'maturity')},
            },
        ),
    ]
