# Generated by Django 5.2.6 on 2025-11-22 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='svg_template',
        ),
        migrations.AddField(
            model_name='background',
            name='background_image',
            field=models.ImageField(blank=True, help_text='배경 이미지 파일(PNG/JPG).', null=True, upload_to='backgrounds/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
