# Generated by Django 4.2.27 on 2025-12-18 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_remove_background_svg_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='아이템 식별 코드 (예: TICKET_REROLL)', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('item_type', models.CharField(choices=[('REROLL', 'Re-roll Ticket'), ('BG_UNLOCK', 'Background Unlock')], max_length=20)),
                ('price', models.PositiveIntegerField(default=10, help_text='구매 가격 (Points)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('is_active', models.BooleanField(default=True, help_text='상점 노출 여부')),
                ('target_background', models.ForeignKey(blank=True, help_text='배경 해금권일 경우 연결된 배경 객체', null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.background')),
            ],
        ),
    ]
