# Generated by Django 5.2.6 on 2025-10-31 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=16)),
                ('base_price', models.PositiveIntegerField(default=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SvgAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('asset_type', models.CharField(choices=[('FISH', 'Fish'), ('BG', 'Background')], max_length=8)),
                ('svg', models.FileField(upload_to='svg/')),
                ('width_px', models.PositiveIntegerField(default=50)),
                ('height_px', models.PositiveIntegerField(default=50)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=16)),
                ('approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aquarium', to=settings.AUTH_USER_MODEL)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.backgroundstyle')),
            ],
        ),
        migrations.CreateModel(
            name='FishTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contributor_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manager.backgroundstyle')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishtanks', to=settings.AUTH_USER_MODEL)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishtanks', to='repositories.repository')),
            ],
            options={
                'unique_together': {('owner', 'repository')},
            },
        ),
        migrations.CreateModel(
            name='FishInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.fishspecies')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishes', to='manager.fishtank')),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('FISH', 'Fish'), ('BG', 'Background')], max_length=8)),
                ('price', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('background', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.backgroundstyle')),
                ('fish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='manager.fishspecies')),
            ],
        ),
        migrations.AddField(
            model_name='fishspecies',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'approved': True, 'asset_type': 'FISH'}, on_delete=django.db.models.deletion.PROTECT, to='manager.svgasset'),
        ),
        migrations.AddField(
            model_name='backgroundstyle',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'approved': True, 'asset_type': 'BG'}, on_delete=django.db.models.deletion.PROTECT, to='manager.svgasset'),
        ),
    ]
