# Generated by Django 5.2.6 on 2025-10-31 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishinstance',
            name='species',
        ),
        migrations.RemoveField(
            model_name='fishinstance',
            name='tank',
        ),
        migrations.AlterUniqueTogether(
            name='fishtank',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='background',
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='fishtank',
            name='repository',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='background',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='fish',
        ),
        migrations.AlterModelOptions(
            name='backgroundstyle',
            options={'verbose_name': '배경 스타일', 'verbose_name_plural': '배경 스타일'},
        ),
        migrations.AlterModelOptions(
            name='fishspecies',
            options={'verbose_name': '물고기 종류', 'verbose_name_plural': '물고기 종류'},
        ),
        migrations.AlterModelOptions(
            name='svgasset',
            options={'verbose_name': 'SVG 에셋', 'verbose_name_plural': 'SVG 에셋'},
        ),
        migrations.RemoveField(
            model_name='fishspecies',
            name='base_price',
        ),
        migrations.AlterField(
            model_name='backgroundstyle',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'approved': True, 'asset_type': 'BG'}, on_delete=django.db.models.deletion.PROTECT, related_name='background_styles', to='manager.svgasset'),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='asset',
            field=models.ForeignKey(limit_choices_to={'approved': True, 'asset_type': 'FISH'}, on_delete=django.db.models.deletion.PROTECT, related_name='fish_species', to='manager.svgasset'),
        ),
        migrations.DeleteModel(
            name='Aquarium',
        ),
        migrations.DeleteModel(
            name='FishInstance',
        ),
        migrations.DeleteModel(
            name='FishTank',
        ),
        migrations.DeleteModel(
            name='ShopItem',
        ),
    ]
