# Generated by Django 5.2.6 on 2025-10-31 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_fishinstance_species_remove_fishinstance_tank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='spawn_weight',
            field=models.PositiveIntegerField(default=100, help_text='가중치가 높을수록 자주 나옵니다.'),
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('BG', 'Background'), ('TICKET', 'Draw Ticket')], max_length=10)),
                ('price', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('asset', models.ForeignKey(blank=True, help_text='상품의 대표 이미지로 사용할 SVG 선택', limit_choices_to={'approved': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_items', to='manager.svgasset')),
            ],
            options={
                'verbose_name': '상점 아이템',
                'verbose_name_plural': '상점 아이템',
            },
        ),
    ]
