# Generated by Django 5.2.6 on 2025-10-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_fishspecies_spawn_weight_shopitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgasset',
            name='asset_type',
            field=models.CharField(choices=[('FISH', 'Fish'), ('BG', 'Background'), ('ITEM', 'Shop Item')], max_length=8),
        ),
    ]
