# Generated by Django 5.2.6 on 2025-10-31 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_svgasset_asset_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='svgasset',
            name='maturity',
            field=models.CharField(blank=True, choices=[('HATCHLING', 'Hatchling (새끼)'), ('JUVENILE', 'Juvenile (유어)'), ('ADULT', 'Adult (성체)')], help_text='물고기(FISH)인 경우에만 선택합니다.', max_length=12, null=True),
        ),
    ]
