# Generated by Django 4.2.27 on 2025-12-19 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repositories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aquarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_path', models.CharField(blank=True, help_text='The relative path to the generated SVG file.', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fishtank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svg_path', models.CharField(blank=True, help_text='The relative path to the generated SVG file.', max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fishtank', to='repositories.repository')),
            ],
        ),
        migrations.CreateModel(
            name='OwnBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user unlocked this background.')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.background')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_backgrounds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'background')},
            },
        ),
        migrations.CreateModel(
            name='ContributionFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible_in_fishtank', models.BooleanField(default=True, help_text='Determines whether this fish is visible in the repository fishtank.')),
                ('is_visible_in_aquarium', models.BooleanField(default=True, help_text='Determines whether this fish is visible in the personal aquarium.')),
                ('aquarium', models.ForeignKey(blank=True, help_text='The aquarium this fish has been added to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishes', to='aquatics.aquarium')),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_fish', to='repositories.contributor')),
                ('fish_species', models.ForeignKey(help_text='The species assigned to this contributor.', on_delete=django.db.models.deletion.PROTECT, to='items.fishspecies')),
            ],
        ),
        migrations.AddField(
            model_name='aquarium',
            name='background',
            field=models.ForeignKey(blank=True, help_text='The background chosen by the user from their collection.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquatics.ownbackground'),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aquarium', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UnlockedFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user unlocked this fish species.')),
                ('fish_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.fishspecies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_fishes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'fish_species')},
            },
        ),
        migrations.CreateModel(
            name='FishtankSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(blank=True, help_text='The background chosen by the contributor for this fishtank.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquatics.ownbackground')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fishtank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='aquatics.fishtank')),
            ],
            options={
                'unique_together': {('fishtank', 'contributor')},
            },
        ),
    ]
