# Generated by Django 4.2.27 on 2025-12-19 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repositories', '0001_initial'),
        ('items', '0001_initial'),
        ('aquatics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='unlockedfish',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_fishes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ownbackground',
            name='background',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.background'),
        ),
        migrations.AddField(
            model_name='ownbackground',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_backgrounds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fishtank',
            name='background',
            field=models.ForeignKey(blank=True, help_text='이 수족관 뷰에 대해 유저가 설정한 배경입니다.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquatics.ownbackground'),
        ),
        migrations.AddField(
            model_name='fishtank',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishtanks', to='repositories.repository'),
        ),
        migrations.AddField(
            model_name='fishtank',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fishtanks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contributionfish',
            name='aquarium',
            field=models.ForeignKey(blank=True, help_text='The aquarium this fish has been added to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fishes', to='aquatics.aquarium'),
        ),
        migrations.AddField(
            model_name='contributionfish',
            name='contributor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_fish', to='repositories.contributor'),
        ),
        migrations.AddField(
            model_name='contributionfish',
            name='fish_species',
            field=models.ForeignKey(help_text='The species assigned to this contributor.', on_delete=django.db.models.deletion.PROTECT, to='items.fishspecies'),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='background',
            field=models.ForeignKey(blank=True, help_text='The background chosen by the user from their collection.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquatics.ownbackground'),
        ),
        migrations.AddField(
            model_name='aquarium',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aquarium', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='unlockedfish',
            unique_together={('user', 'fish_species')},
        ),
        migrations.AlterUniqueTogether(
            name='ownbackground',
            unique_together={('user', 'background')},
        ),
        migrations.AlterUniqueTogether(
            name='fishtank',
            unique_together={('repository', 'user')},
        ),
    ]
