# Generated by Django 5.2.6 on 2025-11-29 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquatics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributionfish',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='contributionfish',
            name='is_visible_in_aquarium',
            field=models.BooleanField(default=True, help_text='Determines whether this fish is visible in the personal aquarium.'),
        ),
        migrations.AddField(
            model_name='contributionfish',
            name='is_visible_in_fishtank',
            field=models.BooleanField(default=True, help_text='Determines whether this fish is visible in the repository fishtank.'),
        ),
    ]
