# Generated by Django 5.2.6 on 2025-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('BACKGROUND', 'Background'), ('FISH', 'Fish')], help_text='Item type (ensures data integrity)', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['type'], name='shop_shop_type_1942da_idx')],
            },
        ),
    ]
