# Generated by Django 4.2.27 on 2025-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("repositories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="default_branch",
            field=models.CharField(default="main", max_length=100),
        ),
        migrations.AddField(
            model_name="repository",
            name="dirty_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="repository",
            name="last_synced_hash",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
