# Generated by Django 5.2.6 on 2025-09-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('repository_id', models.BigAutoField(help_text="Service's internal unique ID", primary_key=True, serialize=False)),
                ('github_repository_id', models.BigIntegerField(help_text="GitHub's immutable unique ID (used for webhooks, etc.)", unique=True)),
                ('repository_full_name', models.CharField(help_text='Display name (owner/repo)', max_length=255)),
                ('commit_count', models.PositiveIntegerField(default=0)),
                ('star_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Repositories',
            },
        ),
    ]
