# Generated by Django 5.2.6 on 2025-09-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['user'], name='github_repo_user_id_6746b0_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['github_repository_id'], name='github_repo_github__199f7c_idx'),
        ),
    ]
