# Generated by Django 5.2.6 on 2025-09-10 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundBook',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('svg_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FishBook',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('svg_bucket_path', models.CharField(max_length=255)),
                ('max_level', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='RepositoryFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.fishbook')),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github.repository')),
            ],
        ),
        migrations.CreateModel(
            name='UserOwnBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False, help_text='Indicates if this is the currently equipped background')),
                ('background', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tanks.backgroundbook')),
            ],
        ),
    ]
