# Generated by Django 5.2.6 on 2025-09-10 10:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tanks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userownbackground',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='repositoryfish',
            index=models.Index(fields=['repository'], name='tanks_repos_reposit_ad070d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repositoryfish',
            unique_together={('fish', 'repository')},
        ),
        migrations.AlterUniqueTogether(
            name='userownbackground',
            unique_together={('user', 'background')},
        ),
    ]
